version: '2'
services:
    db:
        container_name: "postgresql"
        image: postgres
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=changeMe
        ports:
            - 5432:5432
    web:
        container_name: "lampp-php7"
        build: apache
        environment:
            - TERM=xterm
            - UID=${uid}
        ports:
            - 80:80
            - 8000:8000
            - 8080:8080
        volumes:
            - "${home}/public_html:/var/www/html"
            - ./backup/virtual_hosts:/virtual_hosts
        links:
            - db:web
    pgadmin:
        container_name: "pgadmin4"
        image: fenglc/pgadmin4
        environment:
            - DEFAULT_USER=root
            - DEFAULT_PASSWORD=changeMe
        ports:
            - 5050:5050
        links:
            - db:pgadmin
